Fix undefined reference to 'wl_proxy_marshal_constructor_versioned' on allwinner chip
Because the -lwayland-client would use /usr/lib/aarch64-linux-gnu/ lib on allwinner chips, so
 need set abusolute path to it;

In order to appart from rpi, so add CHIP var to distinguish;